###############################################################################
# VMs configs
###############################################################################
vms:
  aem6.1-author-vm:
    enabled: true
  aem6.1-publish-vm:
    enabled: false